// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdpd2ThuXKVq-BEJtkd3coa5ewJC67aEM',
    appId: '1:715605996013:web:fe4ecd8cdfcc4a6e8a77e4',
    messagingSenderId: '715605996013',
    projectId: 'nutritrack-813f8',
    authDomain: 'nutritrack-813f8.firebaseapp.com',
    storageBucket: 'nutritrack-813f8.firebasestorage.app',
    measurementId: 'G-65PFH9KLQY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSxeyE4hERTWvkyBd1V95OBiIauevTe3E',
    appId: '1:715605996013:android:cda97d3ac042a80b8a77e4',
    messagingSenderId: '715605996013',
    projectId: 'nutritrack-813f8',
    storageBucket: 'nutritrack-813f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhudFQQiyksQ1e8d8CRTDocBJkJ4kcTDw',
    appId: '1:715605996013:ios:690335979927f1c58a77e4',
    messagingSenderId: '715605996013',
    projectId: 'nutritrack-813f8',
    storageBucket: 'nutritrack-813f8.firebasestorage.app',
    iosBundleId: 'com.example.nutritrack',
  );
}
